### PR TITLE
Pre v2.0.0: Merging Phobos-API/CLI/CI

### PR DESCRIPTION
**Pull request by hwiedPro**
This PR adds the phobos command line interface and python module to the develop branch. (Replaces #255)
It has been tested with Blender v3.3 LTS.

This PR should increase the phobos major version to 2.0.0.

## Description
These changes make phobos usable as normal python package and also adds command line utils like the CI scripts.
SDF and URDF export have been updated and now include sensor descriptions as well.
SMURF now includes submechanisms.

SRDF support has been dropped, for the time being.
BOBJ mesh export is now included.
It is distinguished between default obj export and obj export for mars.

## Related Issues / ToDo

- [x] ToDo: https://github.com/dfki-ric/phobos/issues/218
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/225
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/245
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/262
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/263
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/268
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/188
- [x] Recheck: https://github.com/dfki-ric/phobos/issues/163
- [x] ToDo: https://github.com/dfki-ric/phobos/issues/120
  - [x] First part is having a smurf import.
  - ~~Second step is having all additional information saved as well~~ --> [v2.1.0](https://github.com/dfki-ric/phobos/milestone/11)
- [x] Get rid of urdfdom dependency
- [x] Fix Submechanism/Hyrodyn Support
- [x] Add documentation

Bonbons:
-  ~~mark joints as loop/cut joints (might be solved by fixing the Submechanism/HyroDyn Support)~~ [v2.1.0](https://github.com/dfki-ric/phobos/milestone/11)
- [x] in-blender command line editing using the robot representation:
    Bascially possible: one can load the blender model to the command line. Loading it back will add a second robot instance. This has not yet been tested properly and will be reconsidered for full support in [v2.1.0](https://github.com/dfki-ric/phobos/milestone/11)
- ~~An editor for kccd meshes~~ --> [v2.1.0](https://github.com/dfki-ric/phobos/milestone/11)

## How Has This Been Tested?
This has been tested as blender addon with blender 3.3.1.
And with python3.8 as command line tool and python package.
The CI tools have been tested with existing setups.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project. Partially, it complies with PEP8
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by movefasta** [comment]
Hello.
We plan to use Phobos actively in our open source project and want to help release a new version. We are ready to test and implement new features of the plugin. Tell me, please, in testing which components of the plugin, our help would be useful?

In particular, we intend to support the ability to import and export scenes (world) in SDF format. According to the wiki, this is currently not possible. Is this planned to be added in v.2?

**Comment by hwiedPro** [comment]
Hi @movefasta ,
your contributions regarding the Scene export are highly appreciated. We are currently specifying the changes to re-add scene support anyways as this is planned to be integrated in v2.1.0.
Please reach out to me via mail, so we can discuss your contribution in detail: henning.wiedemann@uni-bremen.de

Regarding the time schedule we plan to priorize v2.0.0 without scene export to have a cleaned-up and working version of phobos ready quickly, without having to wait for the scene export and some other features. Those can be then put into v2.1.0 subsequently. But also from our side scene support is important, so we want to have it rather sooner than later.

Looking forward to read from you.
Best, 
Henning

**Comment by brothermechanic** [comment]
Hello @hwiedPro
Thank you for developing useful addon!
I'm with @movefasta developing an infrastructure for the production of robots and we want to build it based on the phobos.
Мaybe this is not the best place for correspondence, sorry for that, if I need to create a task for each item - I'm ready to do it!
git branch pre_v2.0.0
git slice https://github.com/dfki-ric/phobos/tree/1dc7d06a45c949bb1f309f206aa0e91220253645

Import issues:

- Can't to get working relative paths
if I import SDF from some path like //test_model/test_model.sdf with relative meshes to this sdf like model://test_model/model/test_model.stl I get this error:
`Mesh with path /media/disk/robossembler/test_model/model:/test_model/model/test_model.dae wasn't found!`
So, for now I use absolute paths.

- **Can't import combined SDF (with included child SDFs)** like
```xml
<?xml version="1.0" encoding="utf-8"?>
<sdf version="1.9">
  <model name="combo-model">
    <pose>0 0 1 0 0 0</pose>
    <include>
      <name>model-1</name>
      <uri>~/model-1</uri>
      <pose>0 0 0 0 0 0</pose>
    </include>
    <include>
      <name>model-2</name>
      <uri>~/model-2</uri>
      <pose>0 0 0 0 0 0</pose>
    </include>
  </model>
</sdf>
```
I get this error with combined SDFs
```py
Traceback (most recent call last):
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/operators/io.py", line 301, in execute
    createRobot(robot)
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/io/phobos2blender.py", line 474, in createRobot
    rootlink = newlinks[str(robot.get_root())]
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/io/xmlrobot.py", line 400, in get_root
    assert root is not None, "No roots detected, invalid URDF."
AssertionError: No roots detected, invalid URDF.
```
- **Can't import 'world'** [world_empty.sdf](https://github.com/dfki-ric/phobos/files/11040898/world_empty.sdf.txt)
```py
Traceback (most recent call last):
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/operators/io.py", line 300, in execute
    robot = core.Robot(inputfile=self.filepath)
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/core/robot.py", line 38, in __init__
    raise e
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/core/robot.py", line 32, in __init__
    super().__init__(xmlfile=xmlfile, submechanisms_file=submechanisms_file, smurffile=smurffile,
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/io/smurfrobot.py", line 94, in __init__
    base_robot = parse_xml(self.xmlfile)
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/io/parser.py", line 42, in parse_xml
    return World.from_xml(xml_root.findall("./world")[0], dialect=file_type, _xmlfile=xml_file)
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/io/base.py", line 322, in from_xml
    return cls.factory[dialect].from_xml(cls, xml, **kwargs)
KeyError: 'sdf'
```
There is 'Re-adding scene-support' in your roadmap, looks like this is it?

- Axes Mismatch.  
When exporting from Solid Works with the [SDF plugin](https://www.youtube.com/playlist?list=PLC-SsBhVny0XrRpYoofHT39dGeGe51UAa), there is a problem that for SDF Z axis as up, and for meshes Y axis as up.  
Can you give an advice for this?

- Armature (joints) silhouettes visually block the model.  
I would like to suggest to you, let me make new mesh silhouettes for armature, [wire](https://ddz4ak4pa3d19.cloudfront.net/cache/15/13/151336245111ab45404a399431a095a5.jpg) like?  

- Degrees of freedom to > Bone Constraints  
Looks like you have wirk in progress for it? It's don't works right.

- There are problems with mesh shadings like shading groups, hard edges and autosmoth.

- A similar import issues has urdf format.

I'm still learning phobos, like object's attributes and exporting, so if you don't mind, I plan to add my comments in the future.

Our team would also like to provide support/developing for your roadmap, please write how you feel about this and what tasks can work be started?

When you plan to release phobos-2.0.0?

Best regards,
brothermechanic@gmail.com

**Comment by hwiedPro** [comment]
Hi @brothermechanic ,
thanks for your interest in phobos.
phobos2.0.0 will only be able to support simple robots in SDF analog to URDF. The support for multiple robots/multiple model-tags per file or the world-tag support will be goal in v2.1.0. I can't promise yet that the include tag will also be supported, but the chances are good.

Priority in v2.0.0 is to get all provided phobos functionalities working with the refactored core. New features can then be added in v2.1.0.

We hope to have 2.0.0 by the end of may.

Regarding your contributions they are highly appreciated. I will clean-up the scene-related refactoring for 2.0.0 by the mid/end of april, and clean-up the branches so that you have a plane base to start from.

Please open an [issue](https://github.com/dfki-ric/phobos/issues/new?assignees=&labels=&template=feature_request.md) for your feature requests. I think the conversations are there easier to follow than here where they get hidden between the bunches of commits. ;)

Thanks in advance and let's keep in touch.
Best,
Henning

**Comment by brothermechanic** [comment]
@hwiedPro  , thanks for the answer!
We will be glad!
Yes, I will open questions soon, no problem.

It looks like Solidworks has a Y Up Axis by default...

**Comment by AlexanderFabisch** [comment]
During installation I got:

```
ModuleNotFoundError: No module named 'trimesh'
```

**Review by AlexanderFabisch — APPROVED** [review]

**Pull request merged**
